management:
  endpoints:
    web:
      exposure:
        include: "health", "info", "prometheus"  # prometheus 포함
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
