#!/bin/sh
echo '🚀 Running pre-push checks...'
./gradlew clean build -x test
./gradlew editorconfigFormat
git fetch --tags --force


if [ $? -ne 0 ]; then
  echo "❌ Pre-push checks failed!"
  exit 1
fi

echo "✅ All pre-push checks passed!"
